### ISSUE TITLE
Error trying to send mails

### ISSUE THREAD

**Issue by briandiaz** [dpacaud/mandrill#10]
Class
groovy.lang.MissingPropertyException
Message
No such property: status for class: java.util.HashMap$Entry

**Comment by rochap01** [comment]
I'm having the same problem. find a solution?

**Comment by gavinheaden** [comment]
I had this issue and it was resolved when I added the missing last character to my mandrill.apiKey.

**Comment by briandiaz** [comment]
This issue happened because i had the parameters in a wrong section of the config.groovy

**Comment by dpacaud** [comment]
All seems well here ;)
I'm closing this issue.
