### ISSUE TITLE
Is this plugin still available?

### ISSUE THREAD

**Issue by tylerevans** [dpacaud/mandrill#12]
Hi

Im trying to install this plugin via Grails compile ":mandrill:0.5"

Yet it's stating it can't find.

Let me know if this plugin is still available- It would greatly help me:)

Thanks
Tyler

**Comment by dpacaud** [comment]
Hi Tyler,

are you trying yo use this plugin with grails 3.0 ?
If so, that may be the reason it can't be found.
I haven't had a chance yet to play around with grails 3.0 and plugin system has changed :(

**Comment by narenlog** [comment]
UPDATE: I forked this project and modified the plugin settings to support grails 1.3.7. Thanks for this plugin!  Forked project can be found on my github profile as "narenlog/mandrill"

---

Hi Damien
I'm trying to install this plugin with grails 1.3.7 and I'm getting this error during install. 

Error resolving plugin [name:mandrill, group:org.grails.plugins, version:latest.integration].
Plugin not found for name [mandrill] and version [not specified]

**Comment by dpacaud** [comment]
Closing this as everything seems solved (cf : https://github.com/grails/grails-core/issues/580)
